In [3]:
#import numpy library
import numpy as np

In [6]:
#Create two square matrices
X = np.array([[1,5,6],[8,5,9],[1,0,3]])
Z = np.array([[12,20,-3],[5,-8,5],[6,9,17]])
print(X, '\n')
print(Z)

[[1 5 6]
 [8 5 9]
 [1 0 3]] 

[[12 20 -3]
 [ 5 -8  5]
 [ 6  9 17]]


In [8]:
#Add and subtract the matrices X and Z
r_added = X.__add__(Z)
r_subtract = X.__sub__(Z)
print(r_added, '\n')
print(r_subtract)

[[13 25  3]
 [13 -3 14]
 [ 7  9 20]] 

[[-11 -15   9]
 [  3  13   4]
 [ -5  -9 -14]]


In [ ]:
#Piecewise multiplication and multiplication of two matrices
r_piecewise = X.__mul__(Z)
r_mul = X.__matmul__(Z)
print(r_piecewise, '\n')
print(r_mul)